// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppBreadcrumb: typeof import('./src/components/AppBreadcrumb.vue')['default']
    MarkdownPage: typeof import('./src/components/MarkdownPage.vue')['default']
    MdiArrowLeftThin: typeof import('~icons/mdi/arrow-left-thin')['default']
    MdiChevronRight: typeof import('~icons/mdi/chevron-right')['default']
    MdiHome: typeof import('~icons/mdi/home')['default']
    NavFooter: typeof import('./src/components/NavFooter.vue')['default']
    NavHeader: typeof import('./src/components/NavHeader.vue')['default']
    NavItem: typeof import('./src/components/NavItem.vue')['default']
    NavLink: typeof import('./src/components/NavLink.vue')['default']
    README: typeof import('./src/components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
