// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ApiForm: typeof import('./src/components/form/ApiForm.vue')['default']
    AppBreadcrumb: typeof import('./src/components/AppBreadcrumb.vue')['default']
    AppPage: typeof import('./src/components/AppPage.vue')['default']
    Checkbox: typeof import('./src/components/form/Checkbox.vue')['default']
    CloseButton: typeof import('./src/components/form/CloseButton.vue')['default']
    ConfirmDelete: typeof import('./src/components/form/ConfirmDelete.vue')['default']
    ErrorSummary: typeof import('./src/components/form/ErrorSummary.vue')['default']
    FormLoading: typeof import('./src/components/form/FormLoading.vue')['default']
    HelloApi: typeof import('./src/components/HelloApi.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InputDescription: typeof import('./src/components/form/InputDescription.vue')['default']
    MarkdownPage: typeof import('./src/components/MarkdownPage.vue')['default']
    MdiChevronRight: typeof import('~icons/mdi/chevron-right')['default']
    MdiHome: typeof import('~icons/mdi/home')['default']
    NavFooter: typeof import('./src/components/NavFooter.vue')['default']
    NavHeader: typeof import('./src/components/NavHeader.vue')['default']
    NavItem: typeof import('./src/components/NavItem.vue')['default']
    NavLink: typeof import('./src/components/NavLink.vue')['default']
    OutlineButton: typeof import('./src/components/form/OutlineButton.vue')['default']
    PrimaryButton: typeof import('./src/components/form/PrimaryButton.vue')['default']
    README: typeof import('./src/components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecondaryButton: typeof import('./src/components/form/SecondaryButton.vue')['default']
    SelectInput: typeof import('./src/components/form/SelectInput.vue')['default']
    ShellCommand: typeof import('./src/components/ShellCommand.vue')['default']
    SrcLink: typeof import('./src/components/SrcLink.vue')['default']
    TextAreaInput: typeof import('./src/components/form/TextAreaInput.vue')['default']
    TextInput: typeof import('./src/components/form/TextInput.vue')['default']
  }
}
