name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v1
      env:          
        ConnectionStrings__DefaultConnection: ${{ secrets.DEFAULTCONNECTION }}
        AuthKeyBase64: ${{ secrets.AUTHKEYBASE64 }}
      with:
        node-version: 16
    - name: Install and build npm
      run: |
        npm install
        npm run build
      working-directory: ./ui

    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0'
        source-url: https://nuget.pkg.github.com/SlaytonNichols/index.json        
        include-prerelease: true
      env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}   
    - name: Build
      run: |
        dotnet build ./api
        dotnet test **/*Tests.csproj