# This is a basic workflow to help you get started with Actions

name: Deploy Prod

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  release:  
    types: [published] 
env:
  AZURE_WEBAPP_NAME: slaytonnichols # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: "." # set this to the path to your web app project, defaults to the repository root

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout 
    - uses: actions/checkout@v2
    - name: Download Artifact
    - uses: actions/download-artifact@v2
      with:
        name: blog
        path: ./blog
          # Deploy to Azure Web apps
    - name: "Run Azure webapp deploy action using publish profile credentials"
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
        package: "./blog"
# For more samples to get started with GitHub Action workflows to deploy to Azure, refer to https://github.com/Azure/actions-workflow-samples
